#!/bin/bash
#/****************************************************************
# *
# * Copyright (c) 2010
# *
# * Fraunhofer Institute for Manufacturing Engineering	
# * and Automation (IPA)
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *
# * Project name: care-o-bot
# * ROS stack name:
# * ROS package name:
# * Description: This file sets the ros environment variables.
# * Usage:
# *     run ". makeconfig" to set environment variables for current terminal
# *     run ". makeconfig -a" to load environment variables via bashrc automatically
# *     run ". makeconfig -g" to set the global git configuration
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *			
# * Author: Florian Weisshardt, email:florian.weisshardt@ipa.fhg.de
# * Supervised by: Florian Weisshardt, email:florian.weisshardt@ipa.fhg.de
# *
# * Date of creation: Jan 2010
# * ToDo:
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *
# * Redistribution and use in source and binary forms, with or without
# * modification, are permitted provided that the following conditions are met:
# *
# *     * Redistributions of source code must retain the above copyright
# *       notice, this list of conditions and the following disclaimer.
# *     * Redistributions in binary form must reproduce the above copyright
# *       notice, this list of conditions and the following disclaimer in the
# *       documentation and/or other materials provided with the distribution.
# *     * Neither the name of the Fraunhofer Institute for Manufacturing 
# *       Engineering and Automation (IPA) nor the names of its
# *       contributors may be used to endorse or promote products derived from
# *       this software without specific prior written permission.
# *
# * This program is free software: you can redistribute it and/or modify
# * it under the terms of the GNU Lesser General Public License LGPL as 
# * published by the Free Software Foundation, either version 3 of the 
# * License, or (at your option) any later version.
# * 
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU Lesser General Public License LGPL for more details.
# * 
# * You should have received a copy of the GNU Lesser General Public 
# * License LGPL along with this program. 
# * If not, see <http://www.gnu.org/licenses/>.
# *
# ****************************************************************/

ROOT=$PWD
if [ "$1" = "-a" ]; then
	echo "source $ROOT/setup.sh $ROOT" >> ~/.bashrc
	. setup.sh $ROOT
elif [ "$1" = "-g" ]; then	# setup global git configuration for correct identification in commit messages
	echo "configuring global git configuration"
	
	echo "name=" ipa-$USER
	echo "email=" $USER@ipa.fhg.de
	
	echo "Is this correct? (Y/N)"
	while read CORRECT ; do
		if [ $CORRECT = "Y" ]; then
			echo git config --global user.name ipa-$USER
			git config --global user.name ipa-$USER
			echo git config --global user.email $USER@ipa.fhg.de
			git config --global user.email $USER@ipa.fhg.de
			echo git config --global github.user ipa-$USER
			git config --global github.user ipa-$USER
			return
		elif  [ $CORRECT = "N" ]; then
			echo "please change the following lines and paste them into the console:"
			echo "git config --global user.name <your username>"
			echo "git config --global user.email <your email address>"
			echo "git config --global github.user <your username>"
			return
		else
			echo "Error: Please enter Y or N"
		fi
	done
else
	. setup.sh $ROOT
fi
