#!/bin/bash

# Author: 
# Florian Weisshardt, mail:florian.weisshardt@ipa.fhg.de
#
# Description:
# This file sets the ros environment variables
#
# Usage:
# run ". makeconfig" to set environment variables for current terminal
# run ". makeconfig -a" to load environment variables via bashrc automatically

export ROOT=$(pwd)

if [ "$1" = "-a" ]; then
	echo "source $ROOT/setup.sh" >> ~/.bashrc
else
	# add path for cob-ros-pkg to $ROS_PACKAGE_PATH
	export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$ROOT/.
	export ROS_STACK_PATH=$ROS_STACK_PATH:$ROOT/.
	export PYTHONPATH=$PYTHONPATH:$ROS_ROOT/core/roslib/src
fi

# define amount of ros prozesses during build for multi-prozessor machines
export ROS_PARALLEL_JOBS=-j2
