#!/bin/bash
#/****************************************************************
# *
# * Copyright (c) 2010
# *
# * Fraunhofer Institute for Manufacturing Engineering	
# * and Automation (IPA)
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *
# * Project name: care-o-bot
# * ROS stack name:
# * ROS package name:
# * Description: This file creates and shows the dependency tree of the care-o-bot
# *     repository. Define all packages you want to include in the variables PACKAGES_XXX.
# * Usage:
# *     run "./showdeps" to create and show the dependency tree of all packages listed below
# *     run "./showdeps -a" to create and show the dependency tree for the cob3_apps stack
# *     run "./showdeps -c" to create and show the dependency tree for the cob3_common stack
# *     run "./showdeps -d" to create and show the dependency tree for the cob3_driver stack
# *     run "./showdeps -e" to create and show the dependency tree for the cob3_extern stack
# *     run "./showdeps -s" to create and show the dependency tree for the cob3_simulation stack
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *			
# * Author: Florian Weisshardt, email:florian.weisshardt@ipa.fhg.de
# * Supervised by: Florian Weisshardt, email:florian.weisshardt@ipa.fhg.de
# *
# * Date of creation: Jan 2010
# * ToDo:
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *
# * Redistribution and use in source and binary forms, with or without
# * modification, are permitted provided that the following conditions are met:
# *
# *     * Redistributions of source code must retain the above copyright
# *       notice, this list of conditions and the following disclaimer.
# *     * Redistributions in binary form must reproduce the above copyright
# *       notice, this list of conditions and the following disclaimer in the
# *       documentation and/or other materials provided with the distribution.
# *     * Neither the name of the Fraunhofer Institute for Manufacturing 
# *       Engineering and Automation (IPA) nor the names of its
# *       contributors may be used to endorse or promote products derived from
# *       this software without specific prior written permission.
# *
# * This program is free software: you can redistribute it and/or modify
# * it under the terms of the GNU Lesser General Public License LGPL as 
# * published by the Free Software Foundation, either version 3 of the 
# * License, or (at your option) any later version.
# * 
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU Lesser General Public License LGPL for more details.
# * 
# * You should have received a copy of the GNU Lesser General Public 
# * License LGPL along with this program. 
# * If not, see <http://www.gnu.org/licenses/>.
# *
# ****************************************************************/

#--------------------------------------------------------------------
# list all packages here
PACKAGES_APPS=\
cob3_teleop,\
cob3_test

PACKAGES_COMMON=\
cob3_msgs,\
cob3_srvs

PACKAGES_DRIVER=\
sick_s300,\
cob3_hokuyo,\
sdh,\
cob3_camera_sensors,\
powercube_chain,\
cob3_arm,\
cob3_arm_ik,\
cob3_platform,\
cob3_tf_broadcaster

PACKAGES_EXTERN=\
libm5api,\
libntcan,\
libpcan,\
libwm4

PACKAGES_SIMULATION=\
cob3_defs,\
cob3_ogre,\
cob3_gazebo

#--------------------------------------------------------------------
# choose stacks
if [ "$1" = "-a" ]; then
	PACKAGES=$PACKAGES_APPS
elif [ "$1" = "-c" ]; then
	PACKAGES=$PACKAGES_COMMON
elif [ "$1" = "-d" ]; then
	PACKAGES=$PACKAGES_DRIVER
elif [ "$1" = "-e" ]; then
	PACKAGES=$PACKAGES_EXTERN
elif [ "$1" = "-s" ]; then
	PACKAGES=$PACKAGES_SIMULATION
else
	PACKAGES=$PACKAGES_COMMON,$PACKAGES_APPS,$PACKAGES_DRIVER,$PACKAGES_EXTERN,$PACKAGES_SIMULATION
fi

# create dependency tree
rxdeps --one --cluster --target=$PACKAGES

# show dependency tree
evince deps.pdf&
