#!/bin/bash
#/****************************************************************
# *
# * Copyright (c) 2010
# *
# * Fraunhofer Institute for Manufacturing Engineering	
# * and Automation (IPA)
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *
# * Project name: care-o-bot
# * ROS stack name:
# * ROS package name:
# * Description: This file creates and shows the dependency tree of the care-o-bot
# *     repository. Define all packages you want to include in the variables PACKAGES_XXX.
# * Usage:
# *     run "./showdeps" to create and show the dependency tree of all packages listed below
# *     run "./showdeps -a" to create and show the dependency tree for the cob_apps stack
# *     run "./showdeps -c" to create and show the dependency tree for the cob_common stack
# *     run "./showdeps -d" to create and show the dependency tree for the cob_driver stack
# *     run "./showdeps -e" to create and show the dependency tree for the cob_extern stack
# *     run "./showdeps -s" to create and show the dependency tree for the cob_simulation stack
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *			
# * Author: Florian Weisshardt, email:florian.weisshardt@ipa.fhg.de
# * Supervised by: Florian Weisshardt, email:florian.weisshardt@ipa.fhg.de
# *
# * Date of creation: Jan 2010
# * ToDo:
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *
# * Redistribution and use in source and binary forms, with or without
# * modification, are permitted provided that the following conditions are met:
# *
# *     * Redistributions of source code must retain the above copyright
# *       notice, this list of conditions and the following disclaimer.
# *     * Redistributions in binary form must reproduce the above copyright
# *       notice, this list of conditions and the following disclaimer in the
# *       documentation and/or other materials provided with the distribution.
# *     * Neither the name of the Fraunhofer Institute for Manufacturing 
# *       Engineering and Automation (IPA) nor the names of its
# *       contributors may be used to endorse or promote products derived from
# *       this software without specific prior written permission.
# *
# * This program is free software: you can redistribute it and/or modify
# * it under the terms of the GNU Lesser General Public License LGPL as 
# * published by the Free Software Foundation, either version 3 of the 
# * License, or (at your option) any later version.
# * 
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU Lesser General Public License LGPL for more details.
# * 
# * You should have received a copy of the GNU Lesser General Public 
# * License LGPL along with this program. 
# * If not, see <http://www.gnu.org/licenses/>.
# *
# ****************************************************************/

#--------------------------------------------------------------------
# list all packages here
PACKAGES_APPS=\
cob_2dnav,\
cob_2dslam,\
cob_bringup,\
cob_dashboard,\
cob_mmcontroller,\
cob_script_server,\
cob_simpledrive,\
cob_simpletrajectories,\
cob_tactiletools,\
cob_teleop,\
cob_webportal

PACKAGES_COMMON=\
cob_description,\
cob_goco,\
cob_machine,\
cob_msgs,\
cob_srvs,\
cob_utilities,\
cob_vision_utils

PACKAGES_DRIVER=\
cob_arm,\
cob_base,\
cob_base_drive_chain,\
cob_battery,\
cob_camera_sensors,\
cob_canopen_motor,\
cob_forcetorque,\
cob_generic_can,\
cob_head_axis,\
cob_hokuyo,\
cob_joint_state_aggregator,\
cob_joy,\
cob_light,\
cob_manipulator,\
cob_powercube_chain,\
cob_relayboard,\
cob_sdh,\
cob_sick_s300,\
cob_torso,\
cob_touch,\
cob_tray,\
cob_undercarriage_ctrl

PACKAGES_EXTERN=\
libm5api,\
libntcan,\
libpcan,\
libphidgets,\
libsiftfast,\
libwm4

PACKAGES_SIMULATION=\
cob_controller_configuration_gazebo,\
cob_gazebo,\
cob_gazebo_worlds,\
cob_ogre

#--------------------------------------------------------------------
# choose stacks
if [ "$1" = "-a" ]; then
	PACKAGES=$PACKAGES_APPS
elif [ "$1" = "-c" ]; then
	PACKAGES=$PACKAGES_COMMON
elif [ "$1" = "-d" ]; then
	PACKAGES=$PACKAGES_DRIVER
elif [ "$1" = "-e" ]; then
	PACKAGES=$PACKAGES_EXTERN
elif [ "$1" = "-s" ]; then
	PACKAGES=$PACKAGES_SIMULATION
else
	PACKAGES=$PACKAGES_COMMON,$PACKAGES_APPS,$PACKAGES_DRIVER,$PACKAGES_EXTERN,$PACKAGES_SIMULATION
fi

# create dependency tree
rxdeps --one --cluster -l --target=$PACKAGES

# show dependency tree
evince deps.pdf&
